### ISSUE TITLE
Aux cable.

### ISSUE THREAD

**Issue by Urrova** [bhagman/Tone#10]
Is possible with the connections gived in the readme.md connect the arduino to a speaker using the AUX input?

**Comment by bhagman** [comment]
(Better late than never -- here for documentation purposes)

You can try to use something like what is shown in the README.md -- but you would need to add a connector for the auxiliary input on your device.  Also, there is a good possibility that the 5 V output from the Arduino board will cause problems on your device (they usually only use 1 V peak to peak).  You can always try, but be aware that it can break your device.
