### ISSUE TITLE
facing problem in uploading the code in arduino nano

### ISSUE THREAD

**Issue by ssks768499** [bhagman/Tone#3]
Arduino 1.8.1, I'm facing the problem in producing the happy birthday melody.
these are the following errors:
    Arduino: 1.8.1 (Windows 10), Board: "Arduino Nano, ATmega328"

Sketch uses 6736 bytes (21%) of program storage space. Maximum is 30720 bytes.
Global variables use 43 bytes (2%) of dynamic memory, leaving 2005 bytes for local variables. Maximum is 2048 bytes.
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 1 of 10: not in sync: resp=0xd8
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 2 of 10: not in sync: resp=0xd8
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 3 of 10: not in sync: resp=0xd8
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 4 of 10: not in sync: resp=0xd8
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 5 of 10: not in sync: resp=0xd8
avrdude: stk500_recv(): programmer is not responding
Problem uploading to board.  See http://www.arduino.cc/en/Guide/Troubleshooting#upload for suggestions.
avrdude: stk500_getsync() attempt 6 of 10: not in sync: resp=0xd8
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 7 of 10: not in sync: resp=0xd8
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 8 of 10: not in sync: resp=0xd8
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 9 of 10: not in sync: resp=0xd8
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 10 of 10: not in sync: resp=0xd8

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
......suggest me to get rid of these issue....

**Comment by bhagman** [comment]
The avrdude errors you're getting are not related to the library.

If I were to hazard a guess though, assuming this is the project you're working with: 

https://www.hackster.io/liss/happy-birthday-melody-on-arduino-nano-with-3-way-polyphony-c80c31

-- you need to disconnect the one speaker that is connected to RX0 (pin 0) as it will contend with the sketch upload.  You can reconnect it after uploading.

Also, I would recommend putting a resistor in-line with the speakers, as they can draw more current than the microcontroller can provide.  Also, it would be a good idea to put a diode across the speakers as well, to avoid any reverse current.
