### ISSUE TITLE
error with tone library

### ISSUE THREAD

**Issue by goodabi** [bhagman/Tone#4]
Hello, Im trying to use the tone library on a small speaker. Here is my sketch:
void setup() {
  #include <Tone.h>
  #define SPEAKER 8
  pinMode (8, OUTPUT);
}
void loop() {
  tone (8, 200, 1000);
  noTone (8);
  delay (1000);
}
  Simple right?? Here is my error message:
'Error compiling for board Arduino Uno WiFi.'

I don't think I'm trying to use wifi for this program so I'm not really sure what this is about. Been trying to problem solve for 30+ mins. I think maybe I'm still too green. lol

Please help. Thanks

**Comment by rmorenojr** [comment]
1.  #include <Tone.h> should be located before the void setup()
2.  You need to instantiate the class Tone to some variable name like tone1:
    Tone tone1;
3. Then you must call out the method play and pass the parameters frequency and the optional duration:
    tone1,play(200,1000);

I hope this helps.
