### ISSUE TITLE
adafruit feather M0 Tone not declared

### ISSUE THREAD

**Issue by jadeye** [bhagman/Tone#5]
Hello
Kinda wondering if it is to work for **adafruit feather M0**:
`ATSAMD21G18 ARM Cortex M0 processor, clocked at 48 MHz and at 3.3V logic`
[Feather M0](https://learn.adafruit.com/adafruit-feather-m0-bluefruit-le)
Lib installed on **arduino 1.8.3** and errored:
`'Tone' was not declared in this scope`
Although: `#include <Tone.h>`

**Comment by bhagman** [comment]
(for documentation purposes)

This library is only for the Atmel/Microchip AVR 8 bit microcontrollers.  There could be a way to port it over to the ARM Cortex M0 and others, but it would require some significant changes.  The Arduino/Wiring built-in `tone()` function will support a single tone, and possibly more, depending on the core implementation for the chip.
