### ISSUE TITLE
Change duty cycle?

### ISSUE THREAD

**Issue by Urrova** [bhagman/Tone#9]
I am making a sinthetizer with arduino and i want to change the duty cycle (eg from from 50% to 25% or 12.5%)
Is possible change the duty cycle of the square wave? Thanks.

**Comment by bhagman** [comment]
(late response -- for documentation purposes)

Not easily in this code -- there could be a way to do it, but it would be a bit out of scope for this library (a square wave generator).  There are other libraries that can do what you need.
